StringA = "i2b2.i2b2metadata.icd10_icd9"
StringB = "c_path"
StringC = "'\\Diagnoses\\'"

String1 = "i2b2.i2b2demodata.patient_dimension"
String2 = "i2b2.i2b2demodata.visit_dimension"
String3 = "patient_num"
String4 = "sex_cd"
String5 = "'F'"
String6 = "active_status_cd"
String7 = "'U'"

String11 = "patient_num"
String22 = "i2b2.i2b2demodata.observation_fact"
String33 = "i2b2.i2b2metadata.icd10_icd9"
String44 = "c_basecode"
String55 = "concept_cd"
String66 = "i2b2.i2b2demodata.patient_dimension"
String77 = "c_tooltip"
String88 = "Diagnoses \\ Diseases of the circulatory system"
